### ISSUE TITLE
Opening txyp (eye and pen) file add a phantom sample

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#112]
![capture](https://cloud.githubusercontent.com/assets/3226576/11914473/cc1236fc-a679-11e5-8bd9-8e44306eaaca.PNG)

This is only a minor aesthetic issue, but it messes up automatic zooming in the selected data view.

**Comment by isolver** [comment]
Also, at least with the txyp example files, the stroke parsing is all messed up because the sample interval varies a lot (up to 1 screen retrace interval), and many samples have the same timestamp.

Maybe need to do some processing of the sample time fields when a file is first loaded to 'fix duplicate timestampes when possible and come up with an ISI threshold that is big enough to handle timestamp variability caused by wintab event poll interval variability by the recording software.

**Comment by Mark-Torrance** [comment]
I'd leave stroke parsing in these files.  I don't think we should take responsibility for trying to clean up data that were collected badly in the first place - and it would be an artificial fix anyway. It nicely highlights the superior quality of GetWrite generated data!

**Comment by isolver** [comment]
I'm assuming this bug is for txyp files only, and not xml files since they do not load at all correctly anymore.

For txyp files, the issue you are seeing is an issue in the two example txyp files in the markwrite test_data folder. The last 3 lines of 2.tab.txyp are:

424415  41193   24987   215
424423  41193   24987   0
427703  55536   43585   830

i.e. there is ~ a 3.3 second jump in time between the last two samples.

Similar for 1.tab.txyp:

257200  35550   25340   291
257204  35550   25340   0
265152  57737   43677   486

So I'm seeing this as a data file issue, not a markwrite issue, for txyp files atleast. Therefore closing bug, there is a separate one open for the xml file issue.

**Comment by Mark-Torrance** [comment]
I'm not sure that it's that simple. That dot is always there, regardless of which selection your are viewing. That's why it messes up selection view zooming. If it was just a feature of the data file then it should disappear if the selection doesn't include those samples. Also, this wasn't a problem in the first MarkWrite versions.

**Comment by Mark-Torrance** [comment]
I've done some checking, with the newest version of MarkWrite and with the 2.tab.txyp test data.
The phantom sample appears around run (pressed sequence) boundaries - txyp files from eye and pen don't have hover data expect that each run ends with a zero pressure sample (don't know how this is actually created). The phantom sample sometimes appears when the selection includes this zero pressure sample. It sometimes appears on the first non-zero pressure sample after the zero pressure sample, and it sometimes doesn't appear at all. See below. Issue means "dot appears". I can't see a pattern.

![capture](https://cloud.githubusercontent.com/assets/3226576/11953348/6b7942b6-a897-11e5-8631-7ba5d68a2459.PNG)

**Comment by isolver** [comment]
OK, thanks for clarifying this. I think the issue maybe a more general
issue with the sample array index lookup tables that are made for series
and / or run start and end sample positions. I think that sometimes the end
index is +1 from what it should be, resulting in one extra sample getting
included when samples are selected for these series / runs.

I'll go though and double check all my indexing and will likely find the
culprit.

**Comment by Mark-Torrance** [comment]
Note that the rogue sample is always at the same location (I'm guessing 0,0).

**Comment by isolver** [comment]
This is now fixed. It was a general issue with the filling in of filtered x,y data, which is done on a series by series basis. Basically the last sample of each sample series was not getting filtered x , y data populated. That is now fixed.

This issue was showing up clearly in the txyp files because they have time isi dt's of 4 and 8 msec (usually two-four 4 msec dt's,  then one 8 msec dt), this was causing the series detection alg to split the data up into a ton of series, as it was using a threshold of < 2 \* calculated_isi, and calculated_isi was == 0.003999 sec in the case of these text files.

So I also made some changes so that files with big isi variability will not result in a huge number of parsed series start : ends. I:
- changed the series boundary threshold to be 3 \* calculated_isi
- also added a 'Maximum Series ISI (msec)' setting in the app settings dialog. If it is set to 0, then the auto calculated threshold mentioned above is used. If it is > 0, it is used as the series isi boundary threshold. So if it is set to 20, a threshold of < 0.020 sec is used.

**Comment by Mark-Torrance** [comment]
This problem is still present in the attached files.

[test_data txyp (eye and pen).zip](https://github.com/isolver/OpenHandWrite/files/100544/test_data.txyp.eye.and.pen.zip)

The distribution of mid-run ISIs (i.e. for series where pressure != 0 - remember that these data do not include samples where pressure = 0) looks like this (I've missed out the ISIs that were not exactly divisible by 4):

| ISI | count |
| --- | --- |
| 4 | 1760 |
| 8 | 9461 |
| 12 | 8 |
| 16 | 168 |
| 20 | 7 |
| 24 | 190 |
| 28 | 27 |
| 32 | 138 |
| 36 | 31 |
| 40 | 121 |
| 44 | 51 |
| 48 | 89 |
| 52 | 51 |
| 56 | 81 |
| 60 | 50 |
| 64 | 38 |
| 68 | 41 |
| 72 | 1 |
| 76 | 29 |
| 80 | 4 |
| 84 | 23 |
| 92 | 9 |
| 96 | 1 |
| 100 | 10 |

and there were some longer ones too. So a mess!

Because we don't have any hover samples in these data, series detection doesn't mean anything. What happens if for these data we just don't detect series (controlled by a setting)? Is that possible?

**Comment by isolver** [comment]
> This problem is still present in the attached files.

I do not see the original issue you found, where I was including 1 extra sample at the end of a selected series. The 'issues' I see in these data files all seem to be from the crazy ISI distribution.
Is this incorrect?

One thing to note is that you can set the used ISI threshold for breaking the sample file into series. Use the "Maximum Series ISI" setting. If non 0, then that value is used to break up the data into series. Perhaps changing it to something like 100 msec for these files would help?

> Because we don't have any hover samples in these data, 
> series detection doesn't mean anything. What happens 
> if for these data we just don't detect series (controlled by a setting)? 

**Q1**: If all samples have pressure > 0, then each pressed run is also a series. Why do we need to disable anything?

However, looking at file 90.txyp for example, there are samples with 0 pressure value, but in each case only the 1 sample is pressure 0, for example:

```
50076   3487    5148    1024
50083   3493    5129    1024
50092   3499    5111    1024
50099   3522    5064    1024
50219   3546    5043    1024
50227   3546    5043    0
50519   3772    5126    1024
50559   3766    5141    1024
50567   3764    5158    1024
50575   3761    5178    1024
50579   3759    5200    1024
50587   3759    5221    1024
50595   3759    5242    1024
50603   3761    5285    1024
50663   3766    5286    1024
50671   3766    5286    0
50791   3747    4910    1024
50911   3775    4938    1024
50919   3775    4938    0
51091   3972    4909    1024
51147   3951    4908    1024
51151   3940    4922    1024
51167   3929    4942    1024
```

**Q2:** How are these single hover samples to be handled?

**Q3:** It also raises the question of whether a minimum series length threshold should be supported, so if a series length is < 2 samples for example, remove those samples from the data when it is being imported. I think the answer to this is also related to the following question...  

**Q4:** Last time I raised the issue of trying to clean up 'garbage' data, your suggestion was that we do not worry about it and leave it up to the researcher to preprocess their data to fix crazy ISI gaps etc. Is this still the way we are going? If so, there is little we can do about files like these. Junk in == junk out. ;)

Thanks.

**Comment by Mark-Torrance** [comment]
> I do not see the original issue you found, where I was including 1 extra sample at the end of a selected series. The 'issues' I see in these data files all seem to be from the crazy ISI distribution.
> Is this incorrect?
> 
> One thing to note is that you can set the used ISI threshold for breaking the sample file into series. Use the "Maximum Series ISI" setting. If non 0, then that value is used to break up the data into series. Perhaps changing it to something like 100 msec for these files would help?

The symptoms are the same here. I've tried setting the series threshold to 100 (maximum permitted) and though this loads quicker, I get the same issue.

![capture](https://cloud.githubusercontent.com/assets/3226576/12515673/63711c40-c121-11e5-8c5c-882856731c1d.PNG)

> **Q1**: If all samples have pressure > 0, then each pressed run is also a series. Why do we need to disable anything?

This is true. The problem is that in these data you can't reliable detect series-run starts and finishes using an ISI criterion (because ISIs are crazy). However it _is_ possible to identify the ends of runs. These are marked by single zero pressure samples. Any after that and before the next pressed sample are then removed in these data, so there are no hover events.

> However, looking at file 90.txyp for example, there are samples with 0 pressure value, but in each case only the 1 sample is pressure 0, for example:

Yes. But see below.

> **Q2:** How are these single hover samples to be handled?

These aren't real samples. They are just end-of-run markers, with the same pen location always the same as the previous, pressed sample. So, more precisely, these are the first sample of a series/run, without location recording. This is how they should be handled, I think:

![capture](https://cloud.githubusercontent.com/assets/3226576/12516608/335b2b90-c126-11e5-9c45-db61a5ba7f68.PNG)

> **Q3:** It also raises the question of whether a minimum series length threshold should be supported, so if a series length is < 2 samples for example, remove those samples from the data when it is being imported. I think the answer to this is also related to the following question...  

Don't think this is needed as well as the ISI threshold selection. See above and below.

> **Q4:** Last time I raised the issue of trying to clean up 'garbage' data, your suggestion was that we do not worry about it and leave it up to the researcher to preprocess their data to fix crazy ISI gaps etc. Is this still the way we are going? If so, there is little we can do about files like these. Junk in == junk out. ;)

Some aspects of these data are garbage, but some are fine. Even with the crazy ISIs we can get accurate (or accurate enough) measures of time to write a letter / word, time that pen is in air before a word, and so forth. I don't think we should try sort out the ISIs (I'm not sure how we could do this). I think my comment before was about trying to get stroke boundaries from them, which I don't see any value in doing. However, there are three reasons to persevere with these data:
- I have loads of it. The files that I send are data that I actually need to analyse.
- Eye and Pen is the only widely used capture and analysis program. Lots of other people have lots of this kind of data.
- GetWrite is better than Eye and Pen, and is free (E&P costs > 500 euros). If we show that we can analyse E&P data, and in doing so flag the inadequacies of E&P then people will be more likely to see openHW as a viably alternative. It's not a competition, exactly, but it's obvsiously good all round if our (free, open source) program wins :)

**Comment by isolver** [comment]
Thank you for clarifying the txyp file format; the txyp importer does not
currently have anything implemented to handle these single sample zero
pressure points. It currently only removes the first row of data from the
file, which seems to always be 0 0 0 0 for some reason.

Anyhow, I'll work on updating the txyp importer to remove these single 0
pressure samples from the created sample array.

Currently, the status field is not used in markwrite at all, for any
supported file formats, so I do not think there is a need to add status
values to samples created from txyp files. The reasoning for not using the
status field is that only the hdf5 file type actually provides status data,
but markwrite needs to work with several input file types that do not
provide sample status. Thus why the ISI is used to parse the sample file
into a set of sample series. Please let me know if there is an issue with
this.

**Comment by isolver** [comment]
Also, in the example of the issue given, here:

![capture](https://cloud.githubusercontent.com/assets/3226576/12515673/63711c40-c121-11e5-8c5c-882856731c1d.PNG)

can you confirm if this only happens when you use the "Move Selection End to Next Run End" action to create a larger selected area? i.e. it does not occur when you use the  " Selected Next [/ Prev] Run" actions?

That seems to be the case for me. Just want to make sure we are seeing the same issue or if you are seeing a larger scoped one than I am.

Thanks again.

**Comment by Mark-Torrance** [comment]
I've spent some more time with this...

This doesn't occur with specific actions. It's to do with how how the raw data file is initially parsed, I think. These occur at some but not all first-press samples (i.e. samples occuring immediately after one of those zero pressure sample row that mark the start of a lifted-pen period). In all cases these samples have meaningful x,y. In some cases this x,y is ignored and the location is understood as 0,0. I can't see any pattern as to when this does and does not occur.

Rogue samples can be seen on the timeline.
![90 eg](https://cloud.githubusercontent.com/assets/3226576/12549857/00fec786-c358-11e5-8d00-153b01ba2ffa.png)![90 eg 2](https://cloud.githubusercontent.com/assets/3226576/12549862/058bf3dc-c358-11e5-8eff-eb1f0432eb5c.png)

Data here from 90.txyp with final column flagging some instances of the problem (Ignore "end series" - I was looking to see if it was something to do with the series-end markers. I tested this with the ISI threshold set to 100 ms):

[txyp 90 00 issue.txt](https://github.com/isolver/OpenHandWrite/files/103138/txyp.90.00.issue.txt)

**Comment by Mark-Torrance** [comment]
> Anyhow, I'll work on updating the txyp importer to remove these single 0 pressure samples from the created sample array. Currently, the status field is not used in markwrite at all, for any supported file formats, so I do not think there is a need to add status values to samples created from txyp files. The reasoning for not using the status field is that only the hdf5 file type actually provides status data, but markwrite needs to work with several input file types that do not provide sample status. Thus why the ISI is used to parse the sample file into a set of sample series. Please let me know if there is an issue with this.

I'm understanding this better now, and I'm really sorry that I didn't think this through properly before. This is the situation as I see it:
- we have four different input file types: GetWrite, Eye&Pen (specific txyp), HandSpy (xml), and generic txyp. Generic txyp don't actually exist. 
- E&P-specific txyp only have run (pressed-series) data, with the ends for runs marked by single zero-pressure samples. HandSpy (xml) data are similar. 
- Both potentially have very messy within-series ISIs with a non-negligible number very substantially above the median. However these data are still usable for many purposes.
- Currently GetWrite hdf5 include sample status codes described here: #108 
- These status codes are read into the pendata array in MarkWrite (that's true, isn't it?)
- These status codes are not currently used in the algorithms for selection action (described here #110) which instead re-compute series and run boundaries based on pressure and ISI (that's true, isn't it?).
- Status codes are potentially valuable in creating custom segment reports.

Where I'm heading is making an argument for creating a status column for E&P-txyp and and xml files and then using this in the selection algorithms and when creating custom reports. This would mean that MarkWrite is potentially capable of processing any digitised pen data, of any format, as long as it can be preprocessed to add a status column. Obviously, if there are no Hover sequences, then selection by series won't give sensible (any) behaviour, and if ISIs are crazy then stroke boundaries won't be meaningful, but that's fine.

This make sense to me, except. I'm concerned by this:

> Thus why the ISI is used to parse the sample file into a set of sample series.

Which suggests there's something that I'm not understanding about the structure of the pendata array....

**Comment by isolver** [comment]
> This is the situation as I see it:
> - we have four different input file types: GetWrite, Eye&Pen (specific txyp), HandSpy (xml), and generic txyp. Generic txyp don't actually exist.
>   ....
> - Status codes are potentially valuable in creating custom segment reports.

All  the points you raise are correct.

> This make sense to me, except. I'm concerned by this:
> 
> > Thus why the ISI is used to parse the sample file into a set of sample series.
> > Which suggests there's something that I'm not understanding about the structure of the pendata array....

I think you are understanding things correctly. 

I think the issue is that I did not know that the E&P format provided sample series markers by inserting dummy 0 pressure samples. Furthermore, the generic txyp file format did not define any such series markers either. Therefore I thought it sensible to use an ISI threshold as a generic way to detect series within the sample data being loaded. This assumption seems to have been incorrect given how crazy the ISI variability can be in some of the file types. So I think your suggestion of switching to use the status field of samples to split the data into series makes sense. 

Anyhow, based on your input, please find below my thoughts on how series detection could be changed. Let me know if you agree and what you think about the xml issue mentioned. 

For files types other than hdf5, the status field will need to be populated as part of the file importing process. If we do it in a consistent way for all file types, then we should still be able to have a single algorithm for series detection. Series detection will be based on sample status, never on sample IS. So series boundaries will be detected by finding samples where status includes FIRST_ENTER. Simply: 
- FIRST_ENTER samples will be the first sample of each series. 
- A series will continue until the sample prior to the next detected FIRST_ENTER or when the end of file (or trial) is reached. 
- Exception: If trial parsing is enabled, the first sample of the each trial will always be the first series starting sample, regardless of sample state.

Here is how I see us adding status data to non hdf5 file types, which has some assumptions you need to verify please. For series detection, the only really important status to set is FIRST_ENTER, however we can fill out the status field more for completeness sake:

1)  txyp  file importer ( Eye&Pen):
- removes first row of data if it is all 0's
- generates sample status by:
  1. when a file starts to be read, a first_series_sample flag is set to true. each row in file is processed as a sample.....
  2. If first_series_sample == true, sample is given status FIRST_ENTER plus either FIRST_PRESS, PRESSED or FIRST_HOVER,HOVER based on that samples pressure. Both cases should be supported so generic txyp files can support having hover sample periods. The first_series_sample flag is set to false.
  3. If first_series_sample == false,  the sample is given a status of PRESSED or HOVER based on their pressure value.
  4. If a sample is found with pressure == 0 and has the same ~~time~~ x and y positions as previous sample, then the sample is discarded and the first_series_sample flag is set to true.

2) txyp file importer (generic):
- same as 1. what matters is how we tell people the txyp file must be structured; it must be structured in the same way as Eye&Pen files are, except they are allowed to have hover periods by having > 1 0 pressure sample in sequence. 

3) xml  file importer:
- The xml data has no pressure value at all. 
- the xml schema does group samples using the strokes element. for example:

```
<strokes start="40527839165" end="40527839165">
<stroke Time="40527823686" X="3625" Y="738"/>
<stroke Time="40527823699" X="3618" Y="736"/>
<stroke Time="40527823713" X="3617" Y="736"/>
<stroke Time="40527823726" X="3619" Y="736"/>
<stroke Time="40527823739" X="3621" Y="737"/>
<stroke Time="40527823753" X="3626" Y="738"/>
<stroke Time="40527823766" X="3631" Y="740"/>
<stroke Time="40527823779" X="3638" Y="744"/>
</strokes>
```
- we could use a strokes element to create series. i.e. each <strokes start="40527839165" end="40527839165">..... </strokes> would equal one series.
- my concern is that, given the number of samples within a <strokes>..... </strokes>, they are actually what we call runs. If this is the case, I am not sure what we should do to determine series grouping, fall back on ISI, but allow a very high threshold, i.e. > 500 msec.
- Note: One strange thing is that in each example xml file we have, it seems that the strokes elements 'start' and 'end' attributes are all the same value within a file. For example, all strokes start and end values equal 40531108774 in the 2_27.xml file.

4) hdf5 file importer:
- uses status data provided.

**Comment by Mark-Torrance** [comment]
> For files types other than hdf5, the status field will need to be populated as part of the file importing process. If we do it in a consistent way for all file types, then we should still be able to have a single algorithm for series detection. Series detection will be based on sample status, never on sample IS. So series boundaries will be detected by finding samples where status includes FIRST_ENTER. Simply:
>     FIRST_ENTER samples will be the first sample of each series.
>     A series will continue until the sample prior to the next detected FIRST_ENTER or when the end of file (or trial) is reached.
>     Exception: If trial parsing is enabled, the first sample of the each trial will always be the first series starting sample, regardless of sample state.

Yes. We also need... If FIRST_ENTER and pressure > 0: FIRST_PRESS else: FIRST_HOVER
Although with E&P txyp we will never get the else. 

With both E&P and xml data FIRST_ENTER and FIRST_PRESS always co-occur. FIRST_HOVER and HOVER never occur. So only two line status's are possible:

[PRESS,FIRST_PRESS,FIRST_ENTER] or [PRESS]

and we need to bear in mind that "first enter" is not meaningful (but is required so that MW selection and report creation will run)

With Eye & Pen data

> Here is how I see us adding status data to non hdf5 file types, which has some assumptions you need to verify please. For series detection, the only really important status to set is FIRST_ENTER, however we can fill out the status field more for completeness sake:
> 
> 1) txyp file importer ( Eye&Pen):
>     removes first row of data if it is all 0's
>     generates sample status by:
>         when a file starts to be read, a first_series_sample flag is set to true. each row in file is processed as a sample.....
>         If first_series_sample == true, sample is given status FIRST_ENTER plus either FIRST_PRESS, PRESSED or FIRST_HOVER,HOVER based on that samples pressure. Both cases should be supported so generic txyp files can support having hover sample periods. The first_series_sample flag is set to false.
>         If first_series_sample == false, the sample is given a status of PRESSED or HOVER based on their pressure value.
>         If a sample is found with pressure == 0 and has the same timestamp as previous sample, then the sample is discarded and the first_series_sample flag is set to true.

What we are aiming for is this

```
time: 2.000 status: [HOVER, FIRST_ENTERED, FIRST_HOVER]
time: 2.008 status: [HOVER]
time: 2.015 status: [PRESS, FIRST_PRESS]
time: 2.023 status: [PRESS]
time: 2.030 status: [PRESS]
time: 2.038 status: [PRESS]
time: 2.045 status: [HOVER, FIRST_HOVER]
time: 2.053 status: [HOVER]
time: 2.060 status: [HOVER]
```

So, yeah, that works, except

> If a sample is found with pressure == 0 and has the same timestamp as previous sample, then the sample is discarded and the first_series_sample flag is set to true.
> This "dummy sample" isn't actually a dummy sample. It has it's own timestamp that is an increment on the previous one. Location is nearly always the same as previous, but not always. I think what they've done is just deleted all but the first zero pressure sample.

So, most generic way of handling this is to have a user setting "Analyse pen-press data only" then do....

if pressure == 0: 
    if pen-press data only: delete row and first_series_sample = True
    else: pass (leave open the possibility of adding some logic here for handling generic txyp if this is ever needed)

> 2) txyp file importer (generic):
> same as 1. what matters is how we tell people the txyp file must be structured; it must be structured in the same way as Eye&Pen files are, except they are allowed to have hover periods by having > 1 0 pressure sample in sequence.

I don't think that works, but because with (hypothetical) generic txyp you are back to having to identify series boundaries defined by ISI. So I suggest we just assume that all txyp are Eye & Pen for the timebeing, but leave open the possibility of adding in logic to handle other other format if these ever emerge. Though I suspect this might involve requiring that people providing these data create their own status column before reading the data into MarkWrite (given issues around ISI craziness / criteria)..

> 3) xml file importer:
> 
> ```
>  <strokes start="40527839165" end="40527839165">
> <stroke Time="40527823686" X="3625" Y="738"/>
> <stroke Time="40527823699" X="3618" Y="736"/>
> <stroke Time="40527823713" X="3617" Y="736"/>
> <stroke Time="40527823726" X="3619" Y="736"/>
> <stroke Time="40527823739" X="3621" Y="737"/>
> <stroke Time="40527823753" X="3626" Y="738"/>
> <stroke Time="40527823766" X="3631" Y="740"/>
> <stroke Time="40527823779" X="3638" Y="744"/>
> </strokes>
> ```
> 
> we could use a strokes element to create series. i.e. each ..... would equal one series.
> my concern is that, given the number of samples within a ..... , they are actually what we call runs. If this is the case, I am not sure what we should do to determine series grouping, fall back on ISI, but allow a very high threshold, i.e. > 500 msec.

So the xml "stroke" is what we are calling run and we do this:

If first sample in "stroke": status = [PRESS,FIRST_PRESS,FIRST_ENTER] 
else: status = [PRESS]

I think that's all that's needed?

> Note: One strange thing is that in each example xml file we have, it seems that the strokes elements 'start' and 'end' attributes are all the same value within a file. For example, all strokes start and end values equal 40531108774 in the 2_27.xml file.

I'm guessing these are then used to create a time-from-start value for each "stroke" when reading data into their analysis program. Bit redundant, though.

> 4) hdf5 file importer:     uses status data provided.

Yes

**Comment by isolver** [comment]
> So, yeah, that works, except
> 
> > If a sample is found with pressure == 0 and has the same timestamp as previous sample, then the 
> > sample is discarded and the first_series_sample flag is set to true.
> 
> This "dummy sample" isn't actually a dummy sample. It has it's own timestamp that is an increment on  the previous one. Location is nearly always the same as previous, but not always. I think what they've done is just deleted all but the first zero pressure sample.

Sorry, that was a mistake on my part, I corrected the comment in one place but not there. I meant:

"If a sample is found with pressure == 0 and has the same x,y position as previous sample, then the sample is discarded and the first_series_sample flag is set to true."

But based on your comments I guess the x,y being the same is not always true, so that can not be used. So for now we will just remove the first zero pressure sample from a sequence of hover samples and use that as the series boundaries; in the E&P files these will always be single samples.

As you say, for future consideration only....
This suggests that if we ever do want to have a 'generic' pen data file, we use an extension other than .txyp and specify the format as simply as possible, while still supporting series boundaries  as well as hover periods. 

One easy way would be to expect an all 0's row added at points in the file anywhere a new series should star.  All other rows would be converted to samples and have a status assigned based on rules basically the same as

**Comment by isolver** [comment]
Sorry Mark, another thought after implementing the change and seeing that in the E&P data these 0 pressure samples are really 'pressed run' boundaries, not 'series' boundaries. 

Basically, for txyp and xml files, a sample series (boundaries defined by samples that have FIRST_ENTERED status) and can be made up of >1 run (boundaries defined by samples with FIRST_PRESS status). Hover state has no relevance here. If this is valid then should we:
1. Use the fixed file parsing for txyp and xml files to define pressed run boundaries (so FIRST_PRESS level flagging only), not series boundaries.
2. Still use an ISI threshold to parse the series level boundaries (so FIRST_ENTERED level flagging), but make it much higher in value. If manually set, The ISI threshold would likely need to be set to 1 second or so, but it could default to the 99% value of the ISI distribution.

Just seems like a real shame to totally loose the distinction between sample series and the sample runs within each series. It seems like useful information to me at least. ;)

**Comment by Mark-Torrance** [comment]
> Sorry, that was a mistake on my part, I corrected the comment in one place but not there. I meant:
> [...] All other rows would be converted to samples and have a status assigned based on rules basically the same as 

Good to all of that. It might be a plan to have the "press data only" setting, though. We can then retain txyp as a generic file type, but acknowledge the limitations of eye and pen data. There would be potential for using this setting in future to automatically set other settings, too (i.e. anything to do with hover).

> Just seems like a real shame to totally loose the distinction between sample series and the sample runs within each series. It seems like useful information to me at least. ;)

I think the bottom line is that in these data we don't know anything about series. So we just need to acknowledge that. I'm suggesting that we make series logically equal to run, which will mean that all segment selections work in a non-scary way. Alternatively we could just have a single FIRST_ENTER at the start of the session, which would be more accurate but would mean that if you accidentally hit a series select action not-nice things would happen. For creating reports, you'd just have to remember that anything to do with series was not meaningful.

**Comment by isolver** [comment]
@Mark-Torrance , was your last comment based on my last or 2nd to last comment? Your post and my last post are within 1 minute of each other, so I want to be sure I know what you are agreeing with. ;) Thanks,

Sol

**Comment by Mark-Torrance** [comment]
> Just seems like a real shame to totally loose the distinction between sample series and the sample runs within each series. It seems like useful information to me at least. ;)

I think the bottom line is that in these data we don't know anything about series. So we just need to acknowledge that. I'm suggesting that we make series logically equal to run, which will mean that all segment selections work in a non-scary way. Alternatively we could just have a single FIRST_ENTER at the start of the session, which would be more accurate but would mean that if you accidentally hit a series select action not-nice things would happen. For creating reports, you'd just have to remember that anything to do with series was not meaningful.

**Comment by Mark-Torrance** [comment]
Editing now. Give me a moment.

**Comment by Mark-Torrance** [comment]
See edited comment above.

**Comment by isolver** [comment]
moving any discussion regarding Series and Run parsing to issue #139. This discussion is kind out of out of scope for this issue.

**Comment by isolver** [comment]
fixed (from what I can tell) with updated file parsing. @Mark-Torrance, please verify when you get next code update and close issue if you agree. thanks.
