### ISSUE TITLE
Error, multiple matched strokes

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#200]
This may well be a problem with how we set up our experiment, rather than an actual bug. But Sol, we really need your help.

We get lots of 

Error, 118 strokes found for sample ix 61:
        Selected Stroke 0:  (0, 0, 61L, 4.767852100543678, 79L, 4.902854236774147)
        Selected Stroke 1:  (2363, 0, 61L, 4.767852100543678, 79L, 4.902854236774147) etc. 

errors when trying to create a raw sample report. I've attached relevant files. This is true, as far as I can tell, for all data that we've collected.

[5103.zip](https://github.com/isolver/OpenHandWrite/files/2502586/5103.zip)
[5013_raw_sample_report_error.txt](https://github.com/isolver/OpenHandWrite/files/2502588/5013_raw_sample_report_error.txt)
[Raw_Sample_Data_Report_5103.txt](https://github.com/isolver/OpenHandWrite/files/2502592/Raw_Sample_Data_Report_5103.txt)

**Comment by Mark-Torrance** [comment]
In case it's helpful, I've just noticed that I'm using markwrite-0.2.2.11-py2.7 - so a much older version from before the 2017-2018 work - and I still get this issue.

**Comment by g-no** [comment]
Is this behaviour solved now?

**Comment by isolver** [comment]
No it is not fixed, just patched so that the stream of warnings is reduced so the report still runs.
As I understand the situation, the resulting report is fine, this is a **big** annoyance only. Please let me know if this is incorrect. 

This issue should be fixed at some point, but if the data is fine, do you want it as a Priority1 to start?
Thanks.

**Comment by Mark-Torrance** [comment]
Without checking back, I don't think stroke boundaries are being calculated correctly. i.e. I'm not sure that the data are fine. Sorry, I really should check properly but won't have a chance till next week. I think this should be top of the list, though.

**Comment by g-no** [comment]
Stephan and I are working on a (hopefully) final way of detecting stroke boundaries in R and I'd like it to be implemented in MarkWrite. This will take a bit more time, so we could postpone this issue until this is done.

**Comment by isolver** [comment]
I'll refrsh my memory and look into it this week. Thanks.

**Comment by Mark-Torrance** [comment]
> Stephan and I are working on a (hopefully) final way of detecting stroke boundaries in R and I'd like it to be implemented in MarkWrite. This will take a bit more time, so we could postpone this issue until this is done.

Fine with me. I'm working with Camilla in Stavanger (Sol, this is a PhD student who is using openHandWrite) from 25th March, just in case you need a deadline :)

**Comment by isolver** [comment]
The pressure. ;)

**Comment by isolver** [comment]
This bug is killing me. ;(

No fix yet, but I have figured out that if the Stroke Detection->Use Pressed Sample Runs Only setting is **unchecked**, then there is no error. If it is checked, then the issue occurs.

So the issue must be specific to the stroke parsing on a run by run basis so that should help narrow down the search.

Sorry for the delay on this one.

**Comment by g-no** [comment]
Then remove the option 'Pressed Sample Runs Only' from the setting ... I doubt that anyone would care.

**Comment by isolver** [comment]
I think I need to fix this properly. @Mark-Torrance what do you think?
I guess current 'work around' is to set it to false in the setting. 
Thanks.

**Comment by Mark-Torrance** [comment]
So with "pressed sample runs only" checked the stroke-detection algorithm only runs over data where pressure > 0? Which seems a sensible setting.

My feeling is that stroke detection within the GUI - i.e. strokes are visible in the timeline and are available as a selection increment - is a valuable part of the system. I know that strokes can be parsed independently on Markwrite, and after markup, but for users who don't want or have the ability to do this, and just for ease-of-markup, having stroke detection within the GUI is good. Given this, ignoring pen-in-air when detecting strokes makes sense.

So, yes, I do think it needs to be fixed. I know that Guido and Stephan have a new approach to detecting strokes, and it might make sense to fix this bug at the same time as implementing the new method. But that's obviously not necessarily the case. 

So, either fix now, or set aside definite time for fixing it and for implementing the new stroke-detection algorithm (I suggest).

**Comment by isolver** [comment]
OK, will leave for now and likely look at it in May.

**Comment by isolver** [comment]
Fixed in 0.4.1. 
Fix is applied to any new data imports.  To correct an __existing__ .mwp file the stroke boundaries must be re-parsed so all the duplicates are removed:
1. Open project in MarkWrite 0.4.1 or higher
2. Open Project Settings dialog
3. Toggle "Use Pressed Run Samples Only Option", set it as you want, but it must be toggled once.
4. Press OK.
5. Say 'Yes' when asked if you want to re-parse stroke boundaries.

Now when you create a report you should not get any warnings, and it runs **much** faster.
